# Generated by Django 6.0.2 on 2026-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("land_mart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="land_size_in_cent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
